name: Run Script with Date Parameter

on:
  workflow_dispatch:
    inputs:
      dates:
        description: 'Monday date separated by space to scrap from WeCook (YYYY-MM-DD format)'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/setup-node@v3
      with:
        node-version: '18'
    
    - run: npm install
    - run: node index.js ${{ github.event.inputs.dates }}
    - uses: actions/checkout@v4
    - run: |
        git config --global user.email "abraham.serena@hotmail.com"
        git config --global user.name "Abraham Serena"
        git add data/
        git commit -m "[bot] Update weekMenuData.json" || exit 0  # Exit gracefully if there's nothing to commit
        git push
